name: Deploy

on: 
  push:
    branches:    
      - main

jobs:
  build:
    name: 🚀 Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['15']
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Installing dependecies
        run: |
          yarn install
        env:
          CI: true
        
      - name: Add remote origin
        run: |
          git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
      - name: Fetching old remote
        run: |
          git fetch --unshallow origin
      
      - name: Deploy to Heroku
        run: |
          git push heroku HEAD:main -f